name: Update fetcher.json

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  update-keys:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to use Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v2  # Updated to use Node.js 20
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run fetcher.py script
      run: python fetcher.py

    - name: Check for changes and commit
      run: |
        git config --global user.name 'tpdctp'
        git config --global user.email 'jtvpremium@outlook.com'
        if [ -n "$(git status --porcelain)" ]; then
          git add fetcher.json
          git commit -m 'Update fetcher.json'
          git pull --rebase origin master
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
